trigger:
- main

pool:
  name: default   # your self-hosted agent pool

steps:
# 1️⃣ Verify Python installation
- script: |
    python --version
    where python
    pip --version
  displayName: 'Verify Python 3.12'

# 2️⃣ Upgrade pip and install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# 3️⃣ Run tests using pytest
- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run pytest'

# 4️⃣ Optional: Build a Python package
- script: |
    python setup.py sdist bdist_wheel
  displayName: 'Build Python package'

# 5️⃣ Optional: Publish package to PyPI (if needed)
# - task: TwineAuthenticate@1
#   inputs:
#     artifactFeed: 'sand'
# - script: |
#     pip install twine
#     twine upload dist/*
#   displayName: 'Publish package'
