trigger:
- main

pool:
  name: Default   # your self-hosted agent pool

steps:
# 1️⃣ Verify Python installation
- script: |
    python --version
    where python
    pip --version
  displayName: 'Verify Python 3.12'

# 2️⃣ Upgrade pip and install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

#

# 4️⃣ Optional: Build Python package (only if setup.py exists)
- script: |
    if exist setup.py (
        python setup.py sdist bdist_wheel
    ) else (
        echo "setup.py not found, skipping package build"
    )
  displayName: 'Build Python package (optional)'

# 5️⃣ Optional: Publish package to PyPI (only if dist folder exists)
# - task: TwineAuthenticate@1
#   inputs:
#     artifactFeed: 'sand'
# - script: |
#     if exist dist (
#         pip install twine
#         twine upload dist/*
#     ) else (
#         echo "No dist folder found, skipping publish"
#     )
#   displayName: 'Publish package (optional)'
