trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  appName: 'my-fastapi-apps'  # Replace with your Azure Web App name
  azureSubscription: 'myserv'  # Replace with your service connection name

steps:
- script: |
    sudo apt update
    sudo apt install -y python3.12 python3.12-venv python3.12-dev
    python3.12 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python 3.12 and dependencies'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive app for deployment'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    startUpCommand: 'bash startup.sh'
  displayName: 'Deploy to Azure Web App'
