trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  pythonVersion: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'myserv'
    appType: 'webAppLinux'
    appName: 'my-fastapi-apps'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    startUpCommand: 'bash startup.sh'
